DROP SCHEMA IF EXISTS address CASCADE;
DROP SCHEMA IF EXISTS party CASCADE;
DROP SCHEMA IF EXISTS document CASCADE;
DROP SCHEMA IF EXISTS source CASCADE;
DROP SCHEMA IF EXISTS bulk_operation CASCADE;
DROP SCHEMA IF EXISTS transaction CASCADE;
DROP SCHEMA IF EXISTS cadastre CASCADE;
DROP SCHEMA IF EXISTS system CASCADE;
DROP SCHEMA IF EXISTS administrative CASCADE;
DROP SCHEMA IF EXISTS application CASCADE;
DROP SCHEMA IF EXISTS opentenure CASCADE;






